### ISSUE TITLE
Error in console in first run of sample code

### ISSUE THREAD

**Issue by cardcomm** [dkasaj/SwiftTipJar-SwiftUI-Example#2]
When running the sample app for the first time after opening an instance of the simulator, I get multiple instances of the following error in the Xcode console:
"2022-10-08 12:58:25.505812-0500 SwiftTipJar SwiftUI Example[10428:160315] [SwiftUI] Publishing changes from background threads is not allowed; make sure to publish values from the main thread (via operators like receive(on:)) on model updates."

Note that this does not happen when I run the sample app again without closing the simulator. 

Do you have any idea what's causing this, and how to work around it? Is it possibly timing related?

Thanks! The code looks great if I can just get past this issue. :) 

EDIT: I get this warning in the code: "Publishing changes from background threads is not allowed; make sure to publish values from the main thread (via operators like receive(on:)) on model updates." 
on the line:
@Published public private(set) var tips: [Tip] = []

**Comment by dkasaj** [comment]
Hi @cardcomm,
Please right-click the package in Project Navigator, choose "Update Package" and you should be set.

The issue has been fixed in package v1.1. on Apr 24 2022, but I guess this Example kept loading v1.0 by default. I've just fixed that as well.
Thanks for reporting and good luck with tips :)
